name: Publish Docker

on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Determine Version
        id: determine-version
        run: |
          if [ "${{ github.ref_type }}" = "tag" ]; then
            VERSION=${{ github.ref_name }}
            VERSION=${VERSION:1}
          else 
            VERSION=${{ github.sha }}-SNAPSHOT
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ steps.determine-version.outputs.version }}
          tags: ${{ secrets.DOCKER_USERNAME }}/ostara-agent:${{ steps.determine-version.outputs.version }},${{ secrets.DOCKER_USERNAME }}/ostara-agent:latest